import { getAuthHeader } from './authService';
const API_URL = process.env.REACT_APP_API_URL || 'http://localhost:8080/api';

export const getMaterialConsumptionHistory = async (materialId, days = 30) => {
  try {
    const response = await fetch(`${API_URL}/materials/${materialId}/consumption-history?days=${days}`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
        ...getAuthHeader()
      }
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({ message: 'Error al obtener historial de consumo' }));
      throw new Error(errorData.message || 'Error al obtener historial de consumo');
    }

    return await response.json();
  } catch (error) {
    console.error('Get consumption history error:', error);
    throw error;
  }
};

export const getMaterialStockIntelligence = async (materialId) => {
  try {
    const response = await fetch(`${API_URL}/materials/${materialId}/stock-intelligence`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
        ...getAuthHeader()
      }
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({ message: 'Error al obtener inteligencia de stock' }));
      throw new Error(errorData.message || 'Error al obtener inteligencia de stock');
    }

    return await response.json();
  } catch (error) {
    console.error('Get stock intelligence error:', error);
    throw error;
  }
};

export const getCriticalMaterials = async () => {
  try {
    const response = await fetch(`${API_URL}/materials/critical-stock`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
        ...getAuthHeader()
      }
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({ message: 'Error al obtener materiales críticos' }));
      throw new Error(errorData.message || 'Error al obtener materiales críticos');
    }

    return await response.json();
  } catch (error) {
    console.error('Get critical materials error:', error);
    throw error;
  }
};

export const getAutoGeneratedRequests = async () => {
  try {
    const response = await fetch(`${API_URL}/material-requests?origin=AUTO_REORDEN`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
        ...getAuthHeader()
      }
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({ message: 'Error al obtener solicitudes automáticas' }));
      throw new Error(errorData.message || 'Error al obtener solicitudes automáticas');
    }

    return await response.json();
  } catch (error) {
    console.error('Get auto-generated requests error:', error);
    throw error;
  }
};

export const generateAutoRequests = async () => {
  try {
    const response = await fetch(`${API_URL}/material-requests/generate-auto`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...getAuthHeader()
      }
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({ message: 'Error al generar solicitudes automáticas' }));
      throw new Error(errorData.message || 'Error al generar solicitudes automáticas');
    }

    return await response.json();
  } catch (error) {
    console.error('Generate auto requests error:', error);
    throw error;
  }
};

