import React, { useState, useEffect } from "react";
import {
  Card,
  CardHeader,
  CardBody,
  CardTitle,
  Table,
  Alert,
  Badge,
  Row,
  Col,
  FormGroup,
  Label,
  Input,
  Button,
  Modal,
  ModalHeader,
  ModalBody,
  ModalFooter,
} from "reactstrap";
import {
  getCriticalMaterials,
  getAutoGeneratedRequests,
  getMaterialStockIntelligence,
  getMaterialConsumptionHistory,
  generateAutoRequests,
} from "services/stockIntelligenceService";
import { getMaterials } from "services/materialService";
import { showError, showSuccess } from "utils/notificationHelper";

function StockIntelligenceDashboard() {
  const [criticalMaterials, setCriticalMaterials] = useState([]);
  const [filteredMaterials, setFilteredMaterials] = useState([]);
  const [autoGeneratedRequests, setAutoGeneratedRequests] = useState([]);
  const [materials, setMaterials] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [priorityFilter, setPriorityFilter] = useState("all");
  const [selectedMaterial, setSelectedMaterial] = useState(null);
  const [materialDetail, setMaterialDetail] = useState(null);
  const [consumptionHistory, setConsumptionHistory] = useState([]);
  const [detailModalOpen, setDetailModalOpen] = useState(false);
  const [generatingRequests, setGeneratingRequests] = useState(false);
  const [confirmModalOpen, setConfirmModalOpen] = useState(false);

  useEffect(() => {
    loadData();
  }, []);

  useEffect(() => {
    filterMaterials();
  }, [criticalMaterials, priorityFilter]);

  const loadData = async () => {
    try {
      setLoading(true);
      setError("");

      const [critical, autoRequests, materialsData] = await Promise.all([
        getCriticalMaterials().catch(() => []),
        getAutoGeneratedRequests().catch(() => []),
        getMaterials().catch(() => []),
      ]);

      setCriticalMaterials(critical || []);
      setAutoGeneratedRequests(autoRequests || []);
      setMaterials(materialsData || []);
    } catch (err) {
      setError(err.message || "Error al cargar datos");
      showError(err.message || "Error al cargar datos");
    } finally {
      setLoading(false);
    }
  };

  const filterMaterials = () => {
    if (priorityFilter === "all") {
      setFilteredMaterials(criticalMaterials);
      return;
    }

    const filtered = criticalMaterials.filter((material) => {
      const stock = parseFloat(material.quantity || 0);
      const reorderPoint = parseFloat(material.reorderPoint || 0);
      const daysOfInventory = parseFloat(material.daysOfInventory || 0);

      if (priorityFilter === "critical") {
        return stock <= 0 || stock < reorderPoint * 0.5;
      } else if (priorityFilter === "high") {
        return stock < reorderPoint && stock > reorderPoint * 0.5;
      } else if (priorityFilter === "medium") {
        return stock >= reorderPoint && daysOfInventory < 30;
      }
      return true;
    });

    setFilteredMaterials(filtered);
  };

  const handleViewDetail = async (material) => {
    try {
      setSelectedMaterial(material);
      setDetailModalOpen(true);
      setMaterialDetail(null);

      const [detail, history] = await Promise.all([
        getMaterialStockIntelligence(material.id),
        getMaterialConsumptionHistory(material.id, 90),
      ]);

      setMaterialDetail(detail);
      setConsumptionHistory(history || []);
    } catch (err) {
      showError("Error al cargar detalles del material");
    }
  };

  const handleGenerateAutoRequests = () => {
    setConfirmModalOpen(true);
  };

  const confirmGenerateAutoRequests = async () => {
    setConfirmModalOpen(false);
    try {
      setGeneratingRequests(true);
      const result = await generateAutoRequests();
      showSuccess(result.message || "Solicitudes generadas exitosamente");
      await loadData();
    } catch (err) {
      showError(err.message || "Error al generar solicitudes automáticas");
    } finally {
      setGeneratingRequests(false);
    }
  };

  const formatCurrency = (amount) => {
    if (!amount) return "Q 0.00";
    return `Q ${parseFloat(amount).toFixed(2)}`;
  };

  const formatDate = (dateString) => {
    if (!dateString) return "-";
    return new Date(dateString).toLocaleDateString("es-GT");
  };

  const formatNumber = (value, decimals = 2) => {
    if (value === null || value === undefined) return "-";
    return parseFloat(value).toFixed(decimals);
  };

  const getStockStatusBadge = (material) => {
    const stock = parseFloat(material.quantity || 0);
    const reorderPoint = parseFloat(material.reorderPoint || 0);

    if (stock <= 0) {
      return <Badge color="danger">Sin Stock</Badge>;
    } else if (stock < reorderPoint) {
      return <Badge color="warning">Bajo Stock</Badge>;
    } else if (stock < (material.min || 0)) {
      return <Badge color="warning">Por Debajo del Mínimo</Badge>;
    } else {
      return <Badge color="success">Normal</Badge>;
    }
  };

  const getPriorityBadge = (material) => {
    const stock = parseFloat(material.quantity || 0);
    const reorderPoint = parseFloat(material.reorderPoint || 0);
    const daysOfInventory = parseFloat(material.daysOfInventory || 0);

    if (stock <= 0 || stock < reorderPoint * 0.5) {
      return <Badge color="danger">Crítico</Badge>;
    } else if (stock < reorderPoint) {
      return <Badge color="warning">Alta</Badge>;
    } else if (daysOfInventory < 30) {
      return <Badge color="info">Media</Badge>;
    }
    return <Badge color="secondary">Baja</Badge>;
  };

  const getSuggestedAction = (material) => {
    const stock = parseFloat(material.quantity || 0);
    const reorderPoint = parseFloat(material.reorderPoint || 0);
    const eoq = parseFloat(material.eoq || 0);

    if (stock <= 0) {
      return `Comprar urgentemente: ${formatNumber(eoq > 0 ? eoq : reorderPoint * 2)} unidades`;
    } else if (stock < reorderPoint) {
      return `Generar solicitud: ${formatNumber(eoq > 0 ? eoq : reorderPoint * 2)} unidades`;
    } else {
      return "Monitorear stock";
    }
  };

  return (
    <div className="content">
      <Row>
        <Col md="12">
          <Card>
            <CardHeader>
              <Row>
                <Col md="8">
                  <CardTitle tag="h4">Dashboard de Inteligencia de Stock</CardTitle>
                </Col>
                <Col md="4" className="text-right">
                  <Button
                    color="success"
                    size="sm"
                    onClick={handleGenerateAutoRequests}
                    disabled={generatingRequests || criticalMaterials.length === 0}
                    className="mr-2"
                  >
                    <i className="nc-icon nc-simple-add" /> Generar Solicitudes
                  </Button>
                  <Button color="primary" size="sm" onClick={loadData}>
                    <i className="nc-icon nc-refresh-69" /> Actualizar
                  </Button>
                </Col>
              </Row>
            </CardHeader>
            <CardBody>
              {error && <Alert color="danger">{error}</Alert>}

              {loading ? (
                <p>Cargando datos...</p>
              ) : (
                <>
                  {/* Resumen */}
                  <Row className="mb-4">
                    <Col md="3">
                      <Card className="bg-danger text-white">
                        <CardBody>
                          <h5>Materiales Críticos</h5>
                          <h2>{criticalMaterials.length}</h2>
                        </CardBody>
                      </Card>
                    </Col>
                    <Col md="3">
                      <Card className="bg-info text-white">
                        <CardBody>
                          <h5>Solicitudes Automáticas</h5>
                          <h2>{autoGeneratedRequests.length}</h2>
                        </CardBody>
                      </Card>
                    </Col>
                    <Col md="3">
                      <Card className="bg-warning text-white">
                        <CardBody>
                          <h5>Total Materiales</h5>
                          <h2>{materials.length}</h2>
                        </CardBody>
                      </Card>
                    </Col>
                    <Col md="3">
                      <Card className="bg-success text-white">
                        <CardBody>
                          <h5>Filtrados</h5>
                          <h2>{filteredMaterials.length}</h2>
                        </CardBody>
                      </Card>
                    </Col>
                  </Row>

                  {/* Filtros */}
                  <Card className="mb-4">
                    <CardBody>
                      <Row>
                        <Col md="4">
                          <FormGroup>
                            <Label>Filtrar por Prioridad</Label>
                            <Input
                              type="select"
                              value={priorityFilter}
                              onChange={(e) => setPriorityFilter(e.target.value)}
                            >
                              <option value="all">Todas las Prioridades</option>
                              <option value="critical">Crítico</option>
                              <option value="high">Alta</option>
                              <option value="medium">Media</option>
                            </Input>
                          </FormGroup>
                        </Col>
                      </Row>
                    </CardBody>
                  </Card>

                  {/* Materiales Críticos */}
                  <Card className="mb-4">
                    <CardHeader>
                      <CardTitle tag="h5">Materiales con Stock Crítico</CardTitle>
                    </CardHeader>
                    <CardBody>
                      {filteredMaterials.length === 0 ? (
                        <p>No hay materiales con stock crítico.</p>
                      ) : (
                        <Table responsive striped>
                          <thead>
                            <tr>
                              <th>SKU</th>
                              <th>Nombre</th>
                              <th>Stock Actual</th>
                              <th>Stock Mínimo</th>
                              <th>Punto de Reorden</th>
                              <th>Días de Inventario</th>
                              <th>Consumo Promedio/Día</th>
                              <th>EOQ</th>
                              <th>Prioridad</th>
                              <th>Estado</th>
                              <th>Acción Sugerida</th>
                              <th>Acciones</th>
                            </tr>
                          </thead>
                          <tbody>
                            {filteredMaterials.map((material) => (
                              <tr key={material.id}>
                                <td>
                                  <strong>{material.sku}</strong>
                                </td>
                                <td>{material.name}</td>
                                <td>{formatNumber(material.quantity, 2)}</td>
                                <td>{formatNumber(material.min, 2)}</td>
                                <td>{formatNumber(material.reorderPoint, 2)}</td>
                                <td>{formatNumber(material.daysOfInventory, 1)} días</td>
                                <td>{formatNumber(material.averageDailyConsumption, 3)}</td>
                                <td>{formatNumber(material.eoq, 2)}</td>
                                <td>{getPriorityBadge(material)}</td>
                                <td>{getStockStatusBadge(material)}</td>
                                <td>
                                  <small>{getSuggestedAction(material)}</small>
                                </td>
                                <td>
                                  <Button
                                    color="info"
                                    size="sm"
                                    onClick={() => handleViewDetail(material)}
                                  >
                                    <i className="nc-icon nc-zoom-split" /> Ver Detalle
                                  </Button>
                                </td>
                              </tr>
                            ))}
                          </tbody>
                        </Table>
                      )}
                    </CardBody>
                  </Card>

                  {/* Solicitudes Generadas Automáticamente */}
                  <Card>
                    <CardHeader>
                      <CardTitle tag="h5">Solicitudes Generadas Automáticamente</CardTitle>
                    </CardHeader>
                    <CardBody>
                      {autoGeneratedRequests.length === 0 ? (
                        <p>No hay solicitudes generadas automáticamente.</p>
                      ) : (
                        <Table responsive striped>
                          <thead>
                            <tr>
                              <th>ID</th>
                              <th>Fecha</th>
                              <th>Origen</th>
                              <th>Materiales</th>
                              <th>Estado</th>
                            </tr>
                          </thead>
                          <tbody>
                            {autoGeneratedRequests.map((request) => (
                              <tr key={request.id}>
                                <td>{request.id}</td>
                                <td>{formatDate(request.requestDate)}</td>
                                <td>
                                  {request.origin === "AUTO_REORDEN" && (
                                    <Badge color="success">Auto Reorden</Badge>
                                  )}
                                  {request.origin === "ORDEN_PRODUCCION" && (
                                    <Badge color="info">Orden de Producción #{request.originReferenceId}</Badge>
                                  )}
                                  {request.origin === "TAREA" && (
                                    <Badge color="warning">Tarea #{request.originReferenceId}</Badge>
                                  )}
                                </td>
                                <td>
                                  {request.items && request.items.length > 0 ? (
                                    <ul style={{ margin: 0, paddingLeft: 20 }}>
                                      {request.items.map((item, idx) => (
                                        <li key={idx}>
                                          {item.materialSku} - {item.materialName}: {formatNumber(item.quantityRequested, 2)}
                                        </li>
                                      ))}
                                    </ul>
                                  ) : (
                                    "-"
                                  )}
                                </td>
                                <td>
                                  <Badge
                                    color={
                                      request.status === "APROBADA"
                                        ? "success"
                                        : request.status === "PENDIENTE"
                                        ? "warning"
                                        : "danger"
                                    }
                                  >
                                    {request.status}
                                  </Badge>
                                </td>
                              </tr>
                            ))}
                          </tbody>
                        </Table>
                      )}
                    </CardBody>
                  </Card>
                </>
              )}
            </CardBody>
          </Card>
        </Col>
      </Row>

      {/* Modal de Detalle de Material */}
      <Modal isOpen={detailModalOpen} toggle={() => setDetailModalOpen(false)} size="lg">
        <ModalHeader toggle={() => setDetailModalOpen(false)}>
          Detalle de Material: {selectedMaterial?.sku} - {selectedMaterial?.name}
        </ModalHeader>
        <ModalBody>
          {materialDetail ? (
            <>
              <Row className="mb-3">
                <Col md="6">
                  <Card className="bg-light">
                    <CardBody>
                      <h6>Información de Stock</h6>
                      <p>
                        <strong>Stock Actual:</strong> {formatNumber(materialDetail.currentStock, 2)}
                      </p>
                      <p>
                        <strong>Stock Mínimo:</strong> {formatNumber(materialDetail.minStock, 2)}
                      </p>
                      <p>
                        <strong>Stock Máximo:</strong> {formatNumber(materialDetail.maxStock, 2)}
                      </p>
                      <p>
                        <strong>Días de Inventario:</strong> {formatNumber(materialDetail.daysOfInventory, 1)} días
                      </p>
                    </CardBody>
                  </Card>
                </Col>
                <Col md="6">
                  <Card className="bg-light">
                    <CardBody>
                      <h6>Métricas de Consumo</h6>
                      <p>
                        <strong>Consumo Diario:</strong> {formatNumber(materialDetail.averageDailyConsumption, 3)}
                      </p>
                      <p>
                        <strong>Consumo Semanal:</strong> {formatNumber(materialDetail.averageWeeklyConsumption, 3)}
                      </p>
                      <p>
                        <strong>Consumo Mensual:</strong> {formatNumber(materialDetail.averageMonthlyConsumption, 3)}
                      </p>
                    </CardBody>
                  </Card>
                </Col>
              </Row>

              <Row className="mb-3">
                <Col md="6">
                  <Card className="bg-light">
                    <CardBody>
                      <h6>Punto de Reorden</h6>
                      <p>
                        <strong>Punto de Reorden:</strong> {formatNumber(materialDetail.reorderPoint, 2)}
                      </p>
                      <p>
                        <strong>Días de Entrega:</strong> {materialDetail.deliveryDays || 7} días
                      </p>
                      <p>
                        <strong>Fórmula:</strong> (Consumo × Lead Time) + Stock Seguridad
                      </p>
                    </CardBody>
                  </Card>
                </Col>
                <Col md="6">
                  <Card className="bg-light">
                    <CardBody>
                      <h6>Cantidad Óptima (EOQ)</h6>
                      <p>
                        <strong>EOQ:</strong> {formatNumber(materialDetail.eoq, 2)} unidades
                      </p>
                      <p>
                        <strong>Fórmula:</strong> √((2 × D × S) / H)
                      </p>
                      <p>
                        <small>
                          D = Demanda anual, S = Costo orden, H = Costo almacenamiento
                        </small>
                      </p>
                    </CardBody>
                  </Card>
                </Col>
              </Row>

              <Card className="mb-3">
                <CardHeader>
                  <CardTitle tag="h6">Historial de Consumo (Últimos 90 días)</CardTitle>
                </CardHeader>
                <CardBody>
                  {consumptionHistory.length === 0 ? (
                    <p>No hay historial de consumo disponible.</p>
                  ) : (
                    <Table responsive size="sm">
                      <thead>
                        <tr>
                          <th>Fecha</th>
                          <th>Cantidad Consumida</th>
                          <th>Origen</th>
                        </tr>
                      </thead>
                      <tbody>
                        {consumptionHistory.slice(0, 10).map((entry) => (
                          <tr key={entry.id}>
                            <td>{formatDate(entry.consumptionDate)}</td>
                            <td>{formatNumber(entry.quantityConsumed, 2)}</td>
                            <td>{entry.source || "-"}</td>
                          </tr>
                        ))}
                      </tbody>
                    </Table>
                  )}
                </CardBody>
              </Card>
            </>
          ) : (
            <p>Cargando detalles...</p>
          )}
        </ModalBody>
        <ModalFooter>
          <Button color="secondary" onClick={() => setDetailModalOpen(false)}>
            Cerrar
          </Button>
        </ModalFooter>
      </Modal>

      {/* Modal de Confirmación para Generar Solicitudes */}
      <Modal isOpen={confirmModalOpen} toggle={() => setConfirmModalOpen(false)}>
        <ModalHeader toggle={() => setConfirmModalOpen(false)}>
          Confirmar Generación de Solicitudes
        </ModalHeader>
        <ModalBody>
          <p>
            ¿Desea generar solicitudes automáticas para todos los materiales críticos?
          </p>
          <p className="text-muted">
            Se generará una solicitud con {criticalMaterials.length} material(es) que están por debajo del punto de reorden.
          </p>
        </ModalBody>
        <ModalFooter>
          <Button
            color="secondary"
            onClick={() => setConfirmModalOpen(false)}
            disabled={generatingRequests}
          >
            Cancelar
          </Button>
          <Button
            color="success"
            onClick={confirmGenerateAutoRequests}
            disabled={generatingRequests}
          >
            {generatingRequests ? (
              <>
                <i className="nc-icon nc-spin nc-refresh-69" /> Generando...
              </>
            ) : (
              <>
                <i className="nc-icon nc-simple-add" /> Generar Solicitudes
              </>
            )}
          </Button>
        </ModalFooter>
      </Modal>
    </div>
  );
}

export default StockIntelligenceDashboard;
